import { StyleSheet } from 'react-native';
import { useTheme as useThemeContext } from './theme/ThemeContext';
import { useMemo } from 'react';

export { useThemeContext as useTheme };

export const createStyles = (colors) => StyleSheet.create({
    containerKeyboard: {
        flex: 1,
        backgroundColor: colors.background,
    },
    container: {
        marginTop: 20,
        marginHorizontal: 20,
        flex: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    tabNavigator: {
        paddingTop: 150,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 2,
        marginTop: 15,
    },
    h1: {
        fontFamily: "Bangers_400Regular",
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 8,
    },
    input3: {
        marginBottom: 16,
    },
    input: {
        width: '100%',
        height: 40,
        borderColor: colors.borderInput,
        borderWidth: 1,
        borderRadius: 5,
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        color: colors.text,
        backgroundColor: colors.inputBg,
        placeholderTextColor: colors.textMuted,
    },
    inputNumber: {
        width: '15%',
        height: 50,
        borderColor: colors.borderInput,
        borderWidth: 1,
        borderRadius: 5,
        marginTop: 10,
        marginRight: 3,
        marginLeft: 3,
        marginBottom: 10,
        paddingHorizontal: 20,
        backgroundColor: colors.inputBgAlt,
        textAlign: 'center',
        fontSize: 20,
        color: colors.text,
        placeholderTextColor: colors.textMuted,
    },
    inputPassword: {
        paddingRight: 40,
        color: colors.text,
    },
    button: {
        backgroundColor: '#fe0000',
        width: '100%',
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 5,
        marginTop: 10,
    },
    stretch: {
        width: '95%',
        height: 180,
        resizeMode: "contain",
    },
    text: {
        fontSize: 18,
        lineHeight: 22,
        fontWeight: 'bold',
        letterSpacing: 0.50,
    },
    buttonText: {
        fontSize: 18,
        lineHeight: 22,
        fontWeight: 'bold',
        letterSpacing: 0.50,
        color: '#fff',
    },
    textContainer: {
        flex: 1,
        padding: 12,
        justifyContent: 'center',
    },
    paragraph: {
        width: '80%',
        marginTop: 20,
        color: colors.text,
    },
    linking: {
        marginBottom: 20,
    },
    link: {
        color: colors.link,
        fontSize: 16,
    },
    errorText: {
        color: colors.danger,
        marginBottom: 20,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    icon: {
        position: 'absolute',
        bottom: 10,
        right: 10,
    },
    profileImage: {
        width: 220,
        height: 220,
        borderRadius: 120,
        marginBottom: 20,
        marginTop: 20,
    },
    nameText: {
        fontSize: 24,
        fontWeight: 'bold',
        lineHeight: 30,
        color: colors.text,
        marginBottom: 8,
    },
    emailText: {
        fontSize: 18,
        lineHeight: 24,
        color: colors.textSecondary,
    },
    titleText: {
        fontSize: 21,
        fontWeight: 'bold',
        lineHeight: 28,
        marginTop: 8,
        marginBottom: 8,
        marginLeft: 8,
        color: colors.text,
    },
    titleSetText: {
        fontSize: 21,
        fontWeight: 'bold',
        lineHeight: 28,
        marginTop: 0,
        marginBottom: 8,
        color: colors.text,
    },
    descriptionText: {
        fontSize: 14,
        lineHeight: 20,
        color: colors.textSecondary,
        marginBottom: 8,
        marginLeft: 8,
    },
    setText: {
        fontSize: 14,
        color: colors.textSecondary,
    },
    imageRoundContainer: {
        width: 150,
        height: 150,
        borderRadius: 75,
        overflow: 'hidden',
        marginBottom: 20,
        backgroundColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    parentImageRectangleContainer: {
        width: "100%",
        aspectRatio: 16 / 9,
        backgroundColor: colors.border,
        borderRadius: 5,
    },
    imageRectangleContainer: {
        width: "100%",
        backgroundColor: colors.border,
        aspectRatio: 16 / 9,
        padding: 15,
        borderRadius: 8,
        alignItems: "center",
    },
    placeholder: {
        color: colors.placeholder,
    },
    editButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: colors.toggleBg,
        padding: 8,
        borderRadius: 5,
    },
    loader: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    hamburger: {
        marginRight: 15,
        padding: 10,
        zIndex: 10,
    },
    hamburgerText: {
        fontSize: 24,
        color: colors.headerTitle,
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 15,
    },
    closeText: {
        fontSize: 45,
        color: colors.closeButton,
    },
    sideBar: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: -250,
        width: 250,
        backgroundColor: colors.sidebarBg,
        padding: 0,
        justifyContent: 'center',
        zIndex: 100,
        elevation: 50,
    },
    listContainer: {
        padding: 16,
        flexGrow: 1,
    },
    card: {
        backgroundColor: colors.surface,
        marginBottom: 20,
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: colors.cardShadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    modelListImage: {
        width: '100%',
        aspectRatio: 4 / 3,
        resizeMode: 'cover',
    },
    modalPlaceHolder: {
        flex: 1,
    },
    modalBackground: {
        flex: 1,
        backgroundColor: colors.surface,
        alignItems: 'center',
        borderTopRightRadius: 16,
        borderTopLeftRadius: 16,
        borderBottomRightRadius: 16,
    },
    modalContainer: {
        width: '100%',
        padding: 20,
        alignItems: 'center',
    },
    modalText: {
        fontSize: 18,
        marginBottom: 20,
        color: colors.text,
    },
    modalCloseButton: {
        padding: 6,
        alignItems: 'center',
        justifyContent: 'center',
        width: 40,
        height: 40,
        borderRadius: 10,
        backgroundColor: colors.accent,
        elevation: 5,
        shadowColor: colors.cardShadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    modalInputFields: {
        width: '100%',
        alignItems: 'center',
    },
    buttonText: {
        color: colors.textLight,
        fontWeight: 'bold',
        fontSize: 20,
        letterSpacing: 0.5,
    },
    openModalButton: {
        position: 'absolute',
        right: 10,
        bottom: 50,
        backgroundColor: colors.accent,
        width: 40,
        height: 40,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: colors.cardShadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    openModalButtonText: {
        flex: 1,
        color: colors.textLight,
        fontSize: 30,
        lineHeight: 37,
    },
    counterLimit: {
        color: colors.danger,
        fontWeight: 'bold',
    },
    textArea: {
        width: '100%',
        height: 120,
        borderColor: colors.borderInput,
        borderWidth: 1,
        padding: 10,
        borderRadius: 8,
        fontSize: 16,
        backgroundColor: colors.surface,
        color: colors.text,
        marginBottom: 10,
        placeholderTextColor: colors.textMuted,
    },
    input2: {
        borderColor: colors.borderInput,
        borderWidth: 1,
        paddingRight: 60,
        paddingLeft: 10,
        fontSize: 16,
        width: '100%',
        height: 40,
        borderRadius: 5,
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 10,
        color: colors.text,
        backgroundColor: colors.inputBg,
        placeholderTextColor: colors.textMuted,
    },
    pickerContainer: {
        width: '100%',
        marginTop: 10,
        marginBottom: 10,
    },
    pickerLabel: {
        position: 'absolute',
        top: -10,
        left: 10,
        fontSize: 16,
        fontWeight: 'bold',
        backgroundColor: colors.pickerBg,
        paddingHorizontal: 5,
        zIndex: 99,
        color: colors.text,
    },
    pickerWrapper: {
        width: '100%',
        height: 45,
        borderColor: colors.borderInput,
        borderWidth: 1,
        borderRadius: 5,
        justifyContent: 'center',
    },
    picker: {
        width: '100%',
        fontSize: 10,
        color: colors.pickerText,
    },
    pickerItem: {
        fontSize: 14,
        color: colors.pickerText,
    },
    floatLabelInput: {
        width: '100%',
        height: 45,
        borderColor: colors.borderInput,
        borderWidth: 1,
        borderRadius: 5,
        marginTop: 10,
        marginBottom: 10,
        paddingHorizontal: 13,
        fontSize: 14,
        color: colors.text,
        backgroundColor: colors.inputBg,
        placeholderTextColor: colors.textMuted,
    },
    counter: {
        position: 'absolute',
        right: 10,
        top: 10,
        fontSize: 14,
        color: colors.textMuted,
        backgroundColor: 'transparent',
    },
    profileImageEditText: {
        color: colors.danger,
        fontWeight: 'bold',
        fontSize: 14,
        textAlign: 'center',
        marginTop: 4,
        marginBottom: 8,
    },
    imagePlaceholder: {
        position: 'absolute',
        marginTop: 10,
        backgroundColor: colors.dangerLight,
        padding: 2,
        borderRadius: 15,
        bottom: 20,
        right: 0,
    },
    flex1: {
        flex: 1,
        backgroundColor: colors.background,
    },
    bold: {
        fontWeight: 'bold',
    },
    setDetailLoadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    setDetailSlideContainer: {
        padding: 16,
        paddingBottom: 40,
    },
    setDetailSlideTitle: {
        fontSize: 18,
        color: colors.text,
    },
    setDetailSlideIntro: {
        fontSize: 14,
        marginBottom: 10,
        color: colors.textSecondary,
    },
    setDetailRatingLabel: {
        fontWeight: 'bold',
        marginRight: 8,
        color: colors.text,
    },
    setDetailQuantityText: {
        marginTop: 4,
    },
    textMissing: {
        color: colors.statusMissing,
    },
    textBroken: {
        color: colors.statusBroken,
    },
    textDiscoloured: {
        color: colors.statusDiscoloured,
    },
    setDetailStatusIcon: {
        marginLeft: 4,
    },
    setDetailToolbar: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 10,
        alignItems: 'center',
    },
    setDetailDropdownBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        borderWidth: 1.5,
        gap: 4,
        borderColor: colors.borderDark,
    },
    setDetailDropdownBtnText: {
        fontSize: 13,
        color: colors.textSecondary,
    },
    setDetailDropdownModalContent: {
        paddingVertical: 8,
    },
    setDetailDropdownModalTitle: {
        marginBottom: 8,
    },
    setDetailSortOption: {
        paddingVertical: 10,
        paddingHorizontal: 16,
    },
    setDetailSortOptionActive: {
        backgroundColor: colors.surfaceAlt,
    },
    setDetailSortOptionText: {
        fontSize: 15,
        color: colors.text,
    },
    setDetailSortOptionTextBold: {
        fontSize: 15,
        fontWeight: 'bold',
        color: colors.text,
    },
    setDetailFilterOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        gap: 10,
    },
    setDetailCounterLabel: {
        width: 120,
        color: colors.text,
    },
    arrowLeft: {
        left: 10,
    },
    arrowRight: {
        right: 10,
    },
    ratingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    divider: {
        height: 1,
        backgroundColor: colors.divider,
        width: '100%',
        marginVertical: 16,
        opacity: 0.15,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
        marginBottom: 16,
        paddingHorizontal: 16,
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        flexShrink: 1,
        color: colors.text,
    },
    headerIcons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    dots: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginVertical: 8,
    },
    dot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginHorizontal: 4,
    },
    imageContainer: {
        position: 'relative',
        width: '100%',
        marginBottom: 16,
        overflow: 'hidden',
    },
    mainImage: {
        width: '100%',
        height: '100%',
        borderRadius: 12,
    },
    imageDeleteIcon: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: colors.toggleBg,
        borderRadius: 16,
        padding: 4,
    },
    arrow: {
        position: 'absolute',
        top: '50%',
        transform: [{translateY: -25}],
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    listItem: {
        flexDirection: 'row',
        marginBottom: 8,
        paddingVertical: 3,
        alignItems: 'center',
        borderTopColor: colors.borderDark,
        borderTopWidth: 1,
        borderRadius: 5,
    },
    image: {
        width: 60,
        height: 60,
        borderRadius: 12,
        marginRight: 10,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: colors.modalOverlay,
        justifyContent: "center",
        alignItems: "center",
    },
    modalContent: {
        width: "85%",
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 20,
        color: colors.text,
    },
    counterRow: {
        flexDirection: "row",
        alignItems: "center",
        marginVertical: 8,
    },
    counterBtn: {
        backgroundColor: colors.primary,
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        elevation: 3,
        shadowColor: colors.cardShadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    counterBtnText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.textLight,
    },
    counterValue: {
        width: 40,
        textAlign: "center",
        fontSize: 16,
        color: colors.text,
    },
    saveButton: {
        backgroundColor: colors.text,
        padding: 12,
        borderRadius: 8,
        alignItems: "center",
        marginVertical: 10,
        elevation: 2,
        shadowColor: colors.cardShadow,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.15,
        shadowRadius: 3,
    },
    setDetailCloseButton: {
        position: "absolute",
        top: 8,
        right: 8,
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: "center",
        alignItems: "center",
        zIndex: 100,
    },
    closeButtonText: {
        fontSize: 36,
        fontWeight: "600",
        lineHeight: 36,
        color: colors.text,
    },
    setDetailPreviewLoader: {marginTop: 16},
    setDetailPreviewPartNumber: {
        textAlign: 'center',
        marginTop: 8,
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
    },
    setDetailPreviewNavRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    setDetailPreviewNavCounter: {
        color: colors.textSecondary,
        fontSize: 13,
    },
    setDetailPreviewImage: {
        marginTop: 16,
        alignSelf: 'center',
    },
    setDetailRatingNoMargin: {
        margin: 0,
        padding: 0,
    },
    setDetailDropdownBtnSort: {
        borderColor: colors.borderDark,
    },
    setDetailDropdownBtnSortText: {
        color: colors.textSecondary,
    },
    homeScreenContainer: {
        flex: 1,
        backgroundColor: colors.background,
    },
    homeListCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: 10,
        marginBottom: 10,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: colors.cardShadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
    },
    homeListThumb: {
        width: 80,
        height: 80,
        resizeMode: 'cover',
    },
    homeListInfo: {
        flex: 1,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    homeListTitle: {
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 20,
        color: colors.text,
        marginBottom: 3,
    },
    homeListDesc: {
        fontSize: 12,
        lineHeight: 16,
        color: colors.textSecondary,
    },
    homeListAvatar: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: colors.border,
        marginRight: 10,
    },
    homeToggleBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 10,
        paddingHorizontal: 16,
    },
    homeToggleRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    homeToggleListButton: {
        marginRight: 10,
    },
    homeSearchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 16,
        marginBottom: 10,
    },
    homeSearchInput: {
        flex: 1,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: colors.borderDark,
        borderRadius: 8,
        fontSize: 16,
        backgroundColor: colors.surface,
        color: colors.text,
        marginRight: 8,
        placeholderTextColor: colors.textMuted,
    },
    homeSearchButton: {
        backgroundColor: colors.primaryLight,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    homeActivityIndicator: {
        margin: 16,
    },
    homeCardGrid: {
        flex: 1,
        margin: 8,
    },
    homeCardTitleText: {
        marginLeft: 0,
    },
    homeCardDescText: {
        marginLeft: 0,
    },
    homeScrollTopButton: {
        position: 'absolute',
        right: 24,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.headerBg,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
        shadowColor: colors.cardShadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    homeScrollTopIcon: {
        marginBottom: 3,
    },
    typeBadge: {
        position: 'absolute',
        top: 6,
        left: 6,
        zIndex: 10,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 10,
    },
    typeBadgeSet: {
        backgroundColor: '#0055BF',
    },
    typeBadgeBord: {
        backgroundColor: '#FE8A18',
    },
    typeBadgeText: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.5,
        textTransform: 'uppercase',
    },
    iconButton: {
        width: 36,
        height: 36,
        borderRadius: 6,
        borderWidth: 1.5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    homeCardBody: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: 8,
        paddingBottom: 10,
        paddingTop: 4,
    },
    homeCardText: {
        flex: 1,
    },
    homeOwnerButton: {
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
        marginTop: 14,
    },
    homeOwnerAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.border,
    },
    containerSlider: {
        width: "100%",
    },
    iconRowSlider: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    labelSlider: {
        fontWeight: "bold",
        fontSize: 14,
        color: colors.textSecondary,
    },
    valueSlider: {
        marginTop: 8,
        fontSize: 12,
        textAlign: "center",
        color: colors.text,
    },
    screenPadding: {
        flex: 1,
        padding: 16,
        backgroundColor: colors.background,
    },
    bordHeaderImage: {
        width: '100%',
        height: 200,
        borderRadius: 12,
    },
    bordActionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    bordActionGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    listViewToggle: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginVertical: 10,
    },
    settingsSectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        lineHeight: 22,
        color: colors.text,
        alignSelf: 'flex-start',
        borderBottomWidth: 1,
        borderBottomColor: colors.borderDark,
        paddingBottom: 6,
        marginBottom: 12,
        width: '100%',
    },
    settingsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 14,
    },
    settingsLabel: {
        fontSize: 14,
        lineHeight: 20,
        color: colors.textSecondary,
        fontWeight: '500',
        flex: 1,
    },
    settingsDeleteLabel: {
        color: colors.danger,
    },
    profilePictureOverlay: {
        flex: 1,
        backgroundColor: colors.overlayLight,
        justifyContent: 'flex-end',
    },
    profilePictureDismissArea: {
        flex: 1,
    },
    profilePictureSheet: {
        backgroundColor: colors.surface,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 36,
    },
    imagePreviewOverlay: {
        flex: 1,
        backgroundColor: colors.overlayDark,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imagePreviewImage: {
        width: '100%',
        height: '100%',
    },
    errorBanner: {
        alignSelf: 'stretch',
        marginBottom: 8,
        backgroundColor: '#8b0000',
        borderRadius: 0,
        padding: 12,
        paddingRight: 36,
        zIndex: 1000,
        elevation: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        overflow: 'hidden',
    },
    errorBannerText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    errorBannerClose: {
        position: 'absolute',
        top: 4,
        right: 6,
        padding: 4,
        zIndex: 1001,
    },
    errorBannerProgressTrack: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 4,
        backgroundColor: 'rgba(255,255,255,0.25)',
    },
    errorBannerProgressFill: {
        height: '100%',
        backgroundColor: '#fff',
    },
});

export const useStyles = () => {
    const { colors } = useThemeContext();
    return useMemo(() => createStyles(colors), [colors]);
};
